kind: PersistentVolume
apiVersion: v1
metadata:
  name: mfs-volume
  labels:
    type: shared
spec:
  storageClassName: lizard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "fq/lizardfs"
    options:
      host: "mfsmaster"
      port: "9421" 
      mfssubfolder: /
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mfs-volume-1
  labels:
    type: shared
spec:
  storageClassName: lizard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "fq/lizardfs"
    options:
      host: "mfsmaster"
      port: "9421"
      mfssubfolder: /
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mfs-volume-2
  labels:
    type: shared
spec:
  storageClassName: lizard
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "fq/lizardfs"
    options:
      host: "mfsmaster"
      port: "9421"
      mfssubfolder: /
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-1
spec:
  storageClassName: lizard
  accessModes:
  - ReadWriteMany
  resources:
     requests:
       storage: 1Gi
  selector: 
    matchLabels:
      type: shared
